### ISSUE TITLE
dev: add processing function for publishers

### ISSUE THREAD

**Issue by EvolveArt** [astraly-labs/pragma-monitoring#11]
**Current Behavior**

We currently loop on the sources mapping and query the latest entry given a couple (pair_id, source)>
When the same source is published by different data providers this leads to the monitoring not updating publisher-related metrics.

**Expected Behavior**

Move publisher-related processing to another task.

**Comment by JordyRo1** [comment]
If I understood correctly, we are calling the GaugeVec `TIME_SINCE_LAST_UPDATE_PUBLISHER` when we are calling `process_data_by_pair_and_sources`. So this will update the time since last update for the last publisher that updated its price before the next round of monitoring. So if we have multiple publishers publishing for the same source, only the time associated with the last one that publish will be updated. The only solution I see in this case, is to implement a task with a smaller interval dedicated to the publisher (smaller than 30s).
